sys_name: null
log_level: INFO

Strip:
  driver: APA102
  num_leds: null
  max_clock_speed_hz: 4000000  # [Hz] 4 MHz is the maximum for "large" strips of more than 500 LEDs.
  initial_brightness: 50  # integer from 0 to 100
  max_brightness: 75  # maximum brightness

MQTT:
  prefix: led
  general_path: "{prefix}/{sys_name}/show/{show_name}/{command}"
  notification_path: "{prefix}/{sys_name}/notification"
  username: None
  password: None

  Broker:
    host: localhost
    port: 1883
    keepalive: 60  # [seconds]
